import re
from typing import Tuple

def is_likely_person(name: str) -> Tuple[bool, str]:
    """
    Sprawdza czy nazwa wygląda na imię i nazwisko człowieka.
    
    Args:
        name (str): Nazwa do sprawdzenia
        
    Returns:
        Tuple[bool, str]: (czy to prawdopodobnie osoba, powód odrzucenia)
    """
    if not name or not isinstance(name, str):
        return False, "empty or invalid input"
    
    # Wyczyść nazwę
    name = name.strip()
    if not name:
        return False, "empty after stripping"
    
    # 1. Sprawdź czy zaczyna się od wielkiej litery
    if not name[0].isupper():
        return False, "does not start with uppercase"
    
    # 2. Sprawdź czy nie zawiera liczb
    if any(char.isdigit() for char in name):
        return False, "contains numbers"
    
    # 3. Sprawdź czy nie kończy się na formy dopełniacza
    dopełniacz_endings = ['ej', 'iej', 'ych', 'ich', 'ych', 'ich']
    if any(name.lower().endswith(ending) for ending in dopełniacz_endings):
        return False, "ends with dopełniacz form"
    
    # 4. Sprawdź czy nie zawiera zakazanych słów
    banned_words = [
        'podcast', 'pogrzeb', 'warsaw', 'śmierć', 'smierc', 'świat', 'swiat',
        'gwiazd', 'gwiazda', 'star', 'stars', 'show', 'program', 'odcinek',
        'episode', 'video', 'film', 'movie', 'channel', 'kanał', 'kanal',
        'studio', 'media', 'news', 'nowości', 'nowosci', 'live', 'stream',
        'broadcast', 'transmisja', 'reportaż', 'reportaz', 'wywiad',
        'interview', 'rozmowa', 'debata', 'dyskusja', 'panel', 'konferencja',
        'event', 'wydarzenie', 'premiera', 'release', 'trailer', 'zwiastun',
        'recenzja', 'review', 'opinia', 'opinion', 'komentarz', 'comment',
        'analiza', 'analysis', 'badanie', 'research', 'raport', 'report',
        'dane', 'data', 'statystyki', 'statistics', 'wyniki', 'results',
        'ranking', 'top', 'lista', 'list', 'chart', 'wykres', 'graph',
        'trend', 'tendencja', 'popularność', 'popularnosc', 'popularity',
        'sukces', 'success', 'hit', 'bestseller', 'bestseller', 'hit',
        'viral', 'wirusowy', 'trending', 'modny', 'fashion', 'moda',
        'style', 'styl', 'design', 'projekt', 'project', 'produkcja',
        'production', 'realizacja', 'realization', 'wytwórnia', 'wytwornia',
        'label', 'firma', 'company', 'corporation', 'spółka', 'spolka',
        'enterprise', 'business', 'biznes', 'startup', 'fundacja',
        'foundation', 'organizacja', 'organization', 'instytut', 'institute',
        'centrum', 'center', 'akademia', 'academy', 'uniwersytet',
        'university', 'szkoła', 'szkola', 'school', 'college', 'uczelnia',
        'faculty', 'wydział', 'wydzial', 'department', 'katedra', 'chair',
        'laboratorium', 'laboratory', 'lab', 'badania', 'research',
        'nauka', 'science', 'technologia', 'technology', 'innowacja',
        'innovation', 'rozwiązanie', 'rozwiazanie', 'solution', 'system',
        'platforma', 'platform', 'aplikacja', 'application', 'app',
        'software', 'oprogramowanie', 'hardware', 'sprzęt', 'sprzet',
        'device', 'urządzenie', 'urzadzenie', 'gadżet', 'gadzet', 'gadget',
        'tool', 'narzędzie', 'narzedzie', 'instrument', 'przyrząd',
        'przyrzad', 'equipment', 'wyposażenie', 'wyposazenie', 'gear',
        'accessory', 'akcesoria', 'dodatki', 'extras', 'bonus', 'premium',
        'exclusive', 'ekskluzywny', 'elitarny', 'elite', 'vip', 'premium',
        'gold', 'srebrny', 'silver', 'brązowy', 'bronzowy', 'bronze',
        'platinum', 'diamond', 'diament', 'rubin', 'ruby', 'szmaragd',
        'emerald', 'safir', 'sapphire', 'opal', 'opal', 'perła', 'perla',
        'pearl', 'jade', 'jadeit', 'agat', 'agate', 'kryształ', 'krysztal',
        'crystal', 'quartz', 'kwarc', 'granit', 'granite', 'marmur',
        'marble', 'drewno', 'wood', 'metal', 'metal', 'stal', 'steel',
        'aluminium', 'aluminum', 'miedź', 'miedz', 'copper', 'brąz',
        'bronz', 'bronze', 'złoto', 'zloto', 'gold', 'srebro', 'silver',
        'platyna', 'platinum', 'tytan', 'titanium', 'wolfram', 'tungsten',
        'nikiel', 'nickel', 'chrom', 'chrome', 'cynk', 'zinc', 'ołówek',
        'olowek', 'lead', 'rtęć', 'rtec', 'mercury', 'arsen', 'arsenic',
        'kadm', 'cadmium', 'tal', 'thallium', 'bizmut', 'bismuth',
        'polon', 'polonium', 'rad', 'radium', 'uran', 'uranium',
        'tor', 'thorium', 'neptun', 'neptunium', 'pluton', 'plutonium',
        'ameryk', 'americium', 'kiur', 'curium', 'berkel', 'berkelium',
        'kaliforn', 'californium', 'einstein', 'einsteinium', 'ferm',
        'fermium', 'mendelew', 'mendelevium', 'nobel', 'nobelium',
        'lawrenc', 'lawrencium', 'rutherford', 'rutherfordium', 'dubn',
        'dubnium', 'seaborg', 'seaborgium', 'bohr', 'bohrium', 'hass',
        'hassium', 'meitner', 'meitnerium', 'darmstadt', 'darmstadtium',
        'roentgen', 'roentgenium', 'copernic', 'copernicium', 'nihon',
        'nihonium', 'flerov', 'flerovium', 'moscov', 'moscovium',
        'livermor', 'livermorium', 'tenness', 'tennessine', 'oganess',
        'oganesson', 'hydrogen', 'wodór', 'wodor', 'helium', 'hel',
        'lithium', 'lit', 'beryllium', 'beryl', 'boron', 'bor', 'carbon',
        'węgiel', 'wegiel', 'nitrogen', 'azot', 'oxygen', 'tlen',
        'fluorine', 'fluor', 'neon', 'sodium', 'sód', 'sod', 'magnesium',
        'magnez', 'aluminum', 'glin', 'silicon', 'krzem', 'phosphorus',
        'fosfor', 'sulfur', 'siarka', 'chlorine', 'chlor', 'argon',
        'potassium', 'potas', 'calcium', 'wapń', 'wapn', 'scandium',
        'skand', 'titanium', 'tytan', 'vanadium', 'wanad', 'chromium',
        'chrom', 'manganese', 'mangan', 'iron', 'żelazo', 'zelazo',
        'cobalt', 'kobalt', 'nickel', 'nikiel', 'copper', 'miedź',
        'miedz', 'zinc', 'cynk', 'gallium', 'gal', 'germanium', 'german',
        'arsenic', 'arsen', 'selenium', 'selen', 'bromine', 'brom',
        'krypton', 'krypton', 'rubidium', 'rubid', 'strontium', 'stronc',
        'yttrium', 'it', 'zirconium', 'cyrkon', 'niobium', 'niob',
        'molybdenum', 'molibden', 'technetium', 'technet', 'ruthenium',
        'ruten', 'rhodium', 'rod', 'palladium', 'pallad', 'silver',
        'srebro', 'cadmium', 'kadm', 'indium', 'ind', 'tin', 'cyna',
        'antimony', 'antymon', 'tellurium', 'tellur', 'iodine', 'jod',
        'xenon', 'ksenon', 'cesium', 'cez', 'barium', 'bar', 'lanthanum',
        'lantan', 'cerium', 'cer', 'praseodymium', 'prazeodym', 'neodymium',
        'neodym', 'promethium', 'promet', 'samarium', 'samar', 'europium',
        'europ', 'gadolinium', 'gadolin', 'terbium', 'terb', 'dysprosium',
        'dysproz', 'holmium', 'holm', 'erbium', 'erb', 'thulium', 'tul',
        'ytterbium', 'iterb', 'lutetium', 'lutet', 'hafnium', 'hafn',
        'tantalum', 'tantal', 'tungsten', 'wolfram', 'rhenium', 'ren',
        'osmium', 'osm', 'iridium', 'iryd', 'platinum', 'platyna',
        'gold', 'złoto', 'zloto', 'mercury', 'rtęć', 'rtec', 'thallium',
        'tal', 'lead', 'ołów', 'olow', 'bismuth', 'bizmut', 'polonium',
        'polon', 'astatine', 'astat', 'radon', 'radon', 'francium',
        'frans', 'radium', 'rad', 'actinium', 'aktyn', 'thorium', 'tor',
        'protactinium', 'protaktyn', 'uranium', 'uran', 'neptunium',
        'neptun', 'plutonium', 'pluton', 'americium', 'ameryk', 'curium',
        'kiur', 'berkelium', 'berkel', 'californium', 'kaliforn',
        'einsteinium', 'einstein', 'fermium', 'ferm', 'mendelevium',
        'mendelew', 'nobelium', 'nobel', 'lawrencium', 'lawrenc',
        'rutherfordium', 'rutherford', 'dubnium', 'dubn', 'seaborgium',
        'seaborg', 'bohrium', 'bohr', 'hassium', 'hass', 'meitnerium',
        'meitner', 'darmstadtium', 'darmstadt', 'roentgenium', 'roentgen',
        'copernicium', 'copernic', 'nihonium', 'nihon', 'flerovium',
        'flerov', 'moscovium', 'moscov', 'livermorium', 'livermor',
        'tennessine', 'tenness', 'oganesson', 'oganess'
    ]
    
    name_lower = name.lower()
    for banned_word in banned_words:
        if banned_word in name_lower:
            return False, f"contains banned word: {banned_word}"
    
    # 5. Sprawdź czy zawiera dwa człony (imię + nazwisko)
    parts = name.split()
    if len(parts) < 2:
        return False, "not two parts (needs first and last name)"
    
    # 6. Sprawdź czy każdy człon ma co najmniej 2 znaki
    if any(len(part) < 2 for part in parts):
        return False, "parts too short (minimum 2 characters each)"
    
    # 7. Sprawdź czy nie ma zbyt wielu członów (max 4)
    if len(parts) > 4:
        return False, "too many parts (max 4 allowed)"
    
    # 8. Sprawdź czy nie zawiera tylko jednej litery w członie
    if any(len(part) == 1 for part in parts):
        return False, "contains single letter parts"
    
    # 9. Sprawdź czy nie zawiera tylko spółgłosek lub samogłosek
    vowels = 'aeiouąęłńóśźż'
    consonants = 'bcdfghjklmnpqrstvwxyzćńśźż'
    
    for part in parts:
        part_lower = part.lower()
        vowel_count = sum(1 for c in part_lower if c in vowels)
        consonant_count = sum(1 for c in part_lower if c in consonants)
        
        if vowel_count == 0 or consonant_count == 0:
            return False, "part contains only vowels or consonants"
    
    # 10. Sprawdź czy nie jest zbyt krótkie lub długie
    if len(name) < 4:
        return False, "too short (minimum 4 characters)"
    
    if len(name) > 50:
        return False, "too long (maximum 50 characters)"
    
    return True, "valid person name"


def filter_person_names(names: list) -> list:
    """
    Filtruje listę nazw, zwracając tylko te które wyglądają na imiona i nazwiska.
    
    Args:
        names (list): Lista nazw do przefiltrowania
        
    Returns:
        list: Lista nazw które wyglądają na imiona i nazwiska
    """
    filtered_names = []
    rejected_names = []
    
    for name in names:
        is_person, reason = is_likely_person(name)
        if is_person:
            filtered_names.append(name)
        else:
            rejected_names.append((name, reason))
    
    if rejected_names:
        print(f"Odrzucone nazwy ({len(rejected_names)}):")
        for name, reason in rejected_names[:10]:  # Pokaż pierwsze 10
            print(f"  - {name}: {reason}")
        if len(rejected_names) > 10:
            print(f"  ... i {len(rejected_names) - 10} więcej")
    
    return filtered_names


if __name__ == "__main__":
    # Test funkcji
    test_names = [
        "Jan Kowalski",
        "Anna Nowak",
        "Piotr Pająk",
        "Włodzisław Duch",
        "Podcast Show",
        "Pogrzeb Joanny",
        "Warsaw Studio",
        "Śmierć Bohatera",
        "A Kowalski",
        "Jan K",
        "123 Jan",
        "Jan Kowalski Ej",
        "Podcast Jan Kowalski",
        "Jan Kowalski Show",
        "Jan Kowalski Program",
        "Jan Kowalski Video",
        "Jan Kowalski Film",
        "Jan Kowalski Movie",
        "Jan Kowalski Channel",
        "Jan Kowalski Kanał",
        "Jan Kowalski Studio",
        "Jan Kowalski Media",
        "Jan Kowalski News",
        "Jan Kowalski Nowości",
        "Jan Kowalski Live",
        "Jan Kowalski Stream",
        "Jan Kowalski Broadcast",
        "Jan Kowalski Transmisja",
        "Jan Kowalski Reportaż",
        "Jan Kowalski Wywiad",
        "Jan Kowalski Interview",
        "Jan Kowalski Rozmowa",
        "Jan Kowalski Debata",
        "Jan Kowalski Dyskusja",
        "Jan Kowalski Panel",
        "Jan Kowalski Konferencja",
        "Jan Kowalski Event",
        "Jan Kowalski Wydarzenie",
        "Jan Kowalski Premiera",
        "Jan Kowalski Release",
        "Jan Kowalski Trailer",
        "Jan Kowalski Zwiastun",
        "Jan Kowalski Recenzja",
        "Jan Kowalski Review",
        "Jan Kowalski Opinia",
        "Jan Kowalski Opinion",
        "Jan Kowalski Komentarz",
        "Jan Kowalski Comment",
        "Jan Kowalski Analiza",
        "Jan Kowalski Analysis",
        "Jan Kowalski Badanie",
        "Jan Kowalski Research",
        "Jan Kowalski Raport",
        "Jan Kowalski Report",
        "Jan Kowalski Dane",
        "Jan Kowalski Data",
        "Jan Kowalski Statystyki",
        "Jan Kowalski Statistics",
        "Jan Kowalski Wyniki",
        "Jan Kowalski Results",
        "Jan Kowalski Ranking",
        "Jan Kowalski Top",
        "Jan Kowalski Lista",
        "Jan Kowalski List",
        "Jan Kowalski Chart",
        "Jan Kowalski Wykres",
        "Jan Kowalski Graph",
        "Jan Kowalski Trend",
        "Jan Kowalski Tendencja",
        "Jan Kowalski Popularność",
        "Jan Kowalski Popularnosc",
        "Jan Kowalski Popularity",
        "Jan Kowalski Sukces",
        "Jan Kowalski Success",
        "Jan Kowalski Hit",
        "Jan Kowalski Bestseller",
        "Jan Kowalski Viral",
        "Jan Kowalski Wirusowy",
        "Jan Kowalski Trending",
        "Jan Kowalski Modny",
        "Jan Kowalski Fashion",
        "Jan Kowalski Moda",
        "Jan Kowalski Style",
        "Jan Kowalski Styl",
        "Jan Kowalski Design",
        "Jan Kowalski Projekt",
        "Jan Kowalski Project",
        "Jan Kowalski Produkcja",
        "Jan Kowalski Production",
        "Jan Kowalski Realizacja",
        "Jan Kowalski Realization",
        "Jan Kowalski Wytwórnia",
        "Jan Kowalski Wytwornia",
        "Jan Kowalski Label",
        "Jan Kowalski Firma",
        "Jan Kowalski Company",
        "Jan Kowalski Corporation",
        "Jan Kowalski Spółka",
        "Jan Kowalski Spolka",
        "Jan Kowalski Enterprise",
        "Jan Kowalski Business",
        "Jan Kowalski Biznes",
        "Jan Kowalski Startup",
        "Jan Kowalski Fundacja",
        "Jan Kowalski Foundation",
        "Jan Kowalski Organizacja",
        "Jan Kowalski Organization",
        "Jan Kowalski Instytut",
        "Jan Kowalski Institute",
        "Jan Kowalski Centrum",
        "Jan Kowalski Center",
        "Jan Kowalski Akademia",
        "Jan Kowalski Academy",
        "Jan Kowalski Uniwersytet",
        "Jan Kowalski University",
        "Jan Kowalski Szkoła",
        "Jan Kowalski Szkola",
        "Jan Kowalski School",
        "Jan Kowalski College",
        "Jan Kowalski Uczelnia",
        "Jan Kowalski Faculty",
        "Jan Kowalski Wydział",
        "Jan Kowalski Wydzial",
        "Jan Kowalski Department",
        "Jan Kowalski Katedra",
        "Jan Kowalski Chair",
        "Jan Kowalski Laboratorium",
        "Jan Kowalski Laboratory",
        "Jan Kowalski Lab",
        "Jan Kowalski Badania",
        "Jan Kowalski Research",
        "Jan Kowalski Nauka",
        "Jan Kowalski Science",
        "Jan Kowalski Technologia",
        "Jan Kowalski Technology",
        "Jan Kowalski Innowacja",
        "Jan Kowalski Innovation",
        "Jan Kowalski Rozwiązanie",
        "Jan Kowalski Rozwiazanie",
        "Jan Kowalski Solution",
        "Jan Kowalski System",
        "Jan Kowalski Platforma",
        "Jan Kowalski Platform",
        "Jan Kowalski Aplikacja",
        "Jan Kowalski Application",
        "Jan Kowalski App",
        "Jan Kowalski Software",
        "Jan Kowalski Oprogramowanie",
        "Jan Kowalski Hardware",
        "Jan Kowalski Sprzęt",
        "Jan Kowalski Sprzet",
        "Jan Kowalski Device",
        "Jan Kowalski Urządzenie",
        "Jan Kowalski Urzadzenie",
        "Jan Kowalski Gadżet",
        "Jan Kowalski Gadzet",
        "Jan Kowalski Gadget",
        "Jan Kowalski Tool",
        "Jan Kowalski Narzędzie",
        "Jan Kowalski Narzedzie",
        "Jan Kowalski Instrument",
        "Jan Kowalski Przyrząd",
        "Jan Kowalski Przyrzad",
        "Jan Kowalski Equipment",
        "Jan Kowalski Wyposażenie",
        "Jan Kowalski Wyposazenie",
        "Jan Kowalski Gear",
        "Jan Kowalski Accessory",
        "Jan Kowalski Akcesoria",
        "Jan Kowalski Dodatki",
        "Jan Kowalski Extras",
        "Jan Kowalski Bonus",
        "Jan Kowalski Premium",
        "Jan Kowalski Exclusive",
        "Jan Kowalski Ekskluzywny",
        "Jan Kowalski Elitarny",
        "Jan Kowalski Elite",
        "Jan Kowalski Vip",
        "Jan Kowalski Gold",
        "Jan Kowalski Srebrny",
        "Jan Kowalski Silver",
        "Jan Kowalski Brązowy",
        "Jan Kowalski Bronzowy",
        "Jan Kowalski Bronze",
        "Jan Kowalski Platinum",
        "Jan Kowalski Diamond",
        "Jan Kowalski Diament",
        "Jan Kowalski Rubin",
        "Jan Kowalski Ruby",
        "Jan Kowalski Szmaragd",
        "Jan Kowalski Emerald",
        "Jan Kowalski Safir",
        "Jan Kowalski Sapphire",
        "Jan Kowalski Opal",
        "Jan Kowalski Perła",
        "Jan Kowalski Perla",
        "Jan Kowalski Pearl",
        "Jan Kowalski Jade",
        "Jan Kowalski Jadeit",
        "Jan Kowalski Agat",
        "Jan Kowalski Agate",
        "Jan Kowalski Kryształ",
        "Jan Kowalski Krysztal",
        "Jan Kowalski Crystal",
        "Jan Kowalski Quartz",
        "Jan Kowalski Kwarc",
        "Jan Kowalski Granit",
        "Jan Kowalski Granite",
        "Jan Kowalski Marmur",
        "Jan Kowalski Marble",
        "Jan Kowalski Drewno",
        "Jan Kowalski Wood",
        "Jan Kowalski Metal",
        "Jan Kowalski Stal",
        "Jan Kowalski Steel",
        "Jan Kowalski Aluminium",
        "Jan Kowalski Aluminum",
        "Jan Kowalski Miedź",
        "Jan Kowalski Miedz",
        "Jan Kowalski Copper",
        "Jan Kowalski Brąz",
        "Jan Kowalski Bronz",
        "Jan Kowalski Złoto",
        "Jan Kowalski Zloto",
        "Jan Kowalski Srebro",
        "Jan Kowalski Platyna",
        "Jan Kowalski Tytan",
        "Jan Kowalski Titanium",
        "Jan Kowalski Wolfram",
        "Jan Kowalski Tungsten",
        "Jan Kowalski Nikiel",
        "Jan Kowalski Nickel",
        "Jan Kowalski Chrom",
        "Jan Kowalski Chrome",
        "Jan Kowalski Cynk",
        "Jan Kowalski Zinc",
        "Jan Kowalski Ołówek",
        "Jan Kowalski Olowek",
        "Jan Kowalski Lead",
        "Jan Kowalski Rtęć",
        "Jan Kowalski Rtec",
        "Jan Kowalski Mercury",
        "Jan Kowalski Arsen",
        "Jan Kowalski Arsenic",
        "Jan Kowalski Kadm",
        "Jan Kowalski Cadmium",
        "Jan Kowalski Tal",
        "Jan Kowalski Thallium",
        "Jan Kowalski Bizmut",
        "Jan Kowalski Bismuth",
        "Jan Kowalski Polon",
        "Jan Kowalski Polonium",
        "Jan Kowalski Rad",
        "Jan Kowalski Radium",
        "Jan Kowalski Uran",
        "Jan Kowalski Uranium",
        "Jan Kowalski Tor",
        "Jan Kowalski Thorium",
        "Jan Kowalski Neptun",
        "Jan Kowalski Neptunium",
        "Jan Kowalski Pluton",
        "Jan Kowalski Plutonium",
        "Jan Kowalski Ameryk",
        "Jan Kowalski Americium",
        "Jan Kowalski Kiur",
        "Jan Kowalski Curium",
        "Jan Kowalski Berkel",
        "Jan Kowalski Berkelium",
        "Jan Kowalski Kaliforn",
        "Jan Kowalski Californium",
        "Jan Kowalski Einstein",
        "Jan Kowalski Einsteinium",
        "Jan Kowalski Ferm",
        "Jan Kowalski Fermium",
        "Jan Kowalski Mendelew",
        "Jan Kowalski Mendelevium",
        "Jan Kowalski Nobel",
        "Jan Kowalski Nobelium",
        "Jan Kowalski Lawrenc",
        "Jan Kowalski Lawrencium",
        "Jan Kowalski Rutherford",
        "Jan Kowalski Rutherfordium",
        "Jan Kowalski Dubn",
        "Jan Kowalski Dubnium",
        "Jan Kowalski Seaborg",
        "Jan Kowalski Seaborgium",
        "Jan Kowalski Bohr",
        "Jan Kowalski Bohrium",
        "Jan Kowalski Hass",
        "Jan Kowalski Hassium",
        "Jan Kowalski Meitner",
        "Jan Kowalski Meitnerium",
        "Jan Kowalski Darmstadt",
        "Jan Kowalski Darmstadtium",
        "Jan Kowalski Roentgen",
        "Jan Kowalski Roentgenium",
        "Jan Kowalski Copernic",
        "Jan Kowalski Copernicium",
        "Jan Kowalski Nihon",
        "Jan Kowalski Nihonium",
        "Jan Kowalski Flerov",
        "Jan Kowalski Flerovium",
        "Jan Kowalski Moscov",
        "Jan Kowalski Moscovium",
        "Jan Kowalski Livermor",
        "Jan Kowalski Livermorium",
        "Jan Kowalski Tenness",
        "Jan Kowalski Tennessine",
        "Jan Kowalski Oganess",
        "Jan Kowalski Oganesson",
        "Jan Kowalski Hydrogen",
        "Jan Kowalski Wodór",
        "Jan Kowalski Wodor",
        "Jan Kowalski Helium",
        "Jan Kowalski Hel",
        "Jan Kowalski Lithium",
        "Jan Kowalski Lit",
        "Jan Kowalski Beryllium",
        "Jan Kowalski Beryl",
        "Jan Kowalski Boron",
        "Jan Kowalski Bor",
        "Jan Kowalski Carbon",
        "Jan Kowalski Węgiel",
        "Jan Kowalski Wegiel",
        "Jan Kowalski Nitrogen",
        "Jan Kowalski Azot",
        "Jan Kowalski Oxygen",
        "Jan Kowalski Tlen",
        "Jan Kowalski Fluorine",
        "Jan Kowalski Fluor",
        "Jan Kowalski Neon",
        "Jan Kowalski Sodium",
        "Jan Kowalski Sód",
        "Jan Kowalski Sod",
        "Jan Kowalski Magnesium",
        "Jan Kowalski Magnez",
        "Jan Kowalski Aluminum",
        "Jan Kowalski Glin",
        "Jan Kowalski Silicon",
        "Jan Kowalski Krzem",
        "Jan Kowalski Phosphorus",
        "Jan Kowalski Fosfor",
        "Jan Kowalski Sulfur",
        "Jan Kowalski Siarka",
        "Jan Kowalski Chlorine",
        "Jan Kowalski Chlor",
        "Jan Kowalski Argon",
        "Jan Kowalski Potassium",
        "Jan Kowalski Potas",
        "Jan Kowalski Calcium",
        "Jan Kowalski Wapń",
        "Jan Kowalski Wapn",
        "Jan Kowalski Scandium",
        "Jan Kowalski Skand",
        "Jan Kowalski Titanium",
        "Jan Kowalski Tytan",
        "Jan Kowalski Vanadium",
        "Jan Kowalski Wanad",
        "Jan Kowalski Chromium",
        "Jan Kowalski Chrom",
        "Jan Kowalski Manganese",
        "Jan Kowalski Mangan",
        "Jan Kowalski Iron",
        "Jan Kowalski Żelazo",
        "Jan Kowalski Zelazo",
        "Jan Kowalski Cobalt",
        "Jan Kowalski Kobalt",
        "Jan Kowalski Nickel",
        "Jan Kowalski Nikiel",
        "Jan Kowalski Copper",
        "Jan Kowalski Miedź",
        "Jan Kowalski Miedz",
        "Jan Kowalski Zinc",
        "Jan Kowalski Cynk",
        "Jan Kowalski Gallium",
        "Jan Kowalski Gal",
        "Jan Kowalski Germanium",
        "Jan Kowalski German",
        "Jan Kowalski Arsenic",
        "Jan Kowalski Arsen",
        "Jan Kowalski Selenium",
        "Jan Kowalski Selen",
        "Jan Kowalski Bromine",
        "Jan Kowalski Brom",
        "Jan Kowalski Krypton",
        "Jan Kowalski Krypton",
        "Jan Kowalski Rubidium",
        "Jan Kowalski Rubid",
        "Jan Kowalski Strontium",
        "Jan Kowalski Stronc",
        "Jan Kowalski Yttrium",
        "Jan Kowalski It",
        "Jan Kowalski Zirconium",
        "Jan Kowalski Cyrkon",
        "Jan Kowalski Niobium",
        "Jan Kowalski Niob",
        "Jan Kowalski Molybdenum",
        "Jan Kowalski Molibden",
        "Jan Kowalski Technetium",
        "Jan Kowalski Technet",
        "Jan Kowalski Ruthenium",
        "Jan Kowalski Ruten",
        "Jan Kowalski Rhodium",
        "Jan Kowalski Rod",
        "Jan Kowalski Palladium",
        "Jan Kowalski Pallad",
        "Jan Kowalski Silver",
        "Jan Kowalski Srebro",
        "Jan Kowalski Cadmium",
        "Jan Kowalski Kadm",
        "Jan Kowalski Indium",
        "Jan Kowalski Ind",
        "Jan Kowalski Tin",
        "Jan Kowalski Cyna",
        "Jan Kowalski Antimony",
        "Jan Kowalski Antymon",
        "Jan Kowalski Tellurium",
        "Jan Kowalski Tellur",
        "Jan Kowalski Iodine",
        "Jan Kowalski Jod",
        "Jan Kowalski Xenon",
        "Jan Kowalski Ksenon",
        "Jan Kowalski Cesium",
        "Jan Kowalski Cez",
        "Jan Kowalski Barium",
        "Jan Kowalski Bar",
        "Jan Kowalski Lanthanum",
        "Jan Kowalski Lantan",
        "Jan Kowalski Cerium",
        "Jan Kowalski Cer",
        "Jan Kowalski Praseodymium",
        "Jan Kowalski Prazeodym",
        "Jan Kowalski Neodymium",
        "Jan Kowalski Neodym",
        "Jan Kowalski Promethium",
        "Jan Kowalski Promet",
        "Jan Kowalski Samarium",
        "Jan Kowalski Samar",
        "Jan Kowalski Europium",
        "Jan Kowalski Europ",
        "Jan Kowalski Gadolinium",
        "Jan Kowalski Gadolin",
        "Jan Kowalski Terbium",
        "Jan Kowalski Terb",
        "Jan Kowalski Dysprosium",
        "Jan Kowalski Dysproz",
        "Jan Kowalski Holmium",
        "Jan Kowalski Holm",
        "Jan Kowalski Erbium",
        "Jan Kowalski Erb",
        "Jan Kowalski Thulium",
        "Jan Kowalski Tul",
        "Jan Kowalski Ytterbium",
        "Jan Kowalski Iterb",
        "Jan Kowalski Lutetium",
        "Jan Kowalski Lutet",
        "Jan Kowalski Hafnium",
        "Jan Kowalski Hafn",
        "Jan Kowalski Tantalum",
        "Jan Kowalski Tantal",
        "Jan Kowalski Tungsten",
        "Jan Kowalski Wolfram",
        "Jan Kowalski Rhenium",
        "Jan Kowalski Ren",
        "Jan Kowalski Osmium",
        "Jan Kowalski Osm",
        "Jan Kowalski Iridium",
        "Jan Kowalski Iryd",
        "Jan Kowalski Platinum",
        "Jan Kowalski Platyna",
        "Jan Kowalski Gold",
        "Jan Kowalski Złoto",
        "Jan Kowalski Zloto",
        "Jan Kowalski Mercury",
        "Jan Kowalski Rtęć",
        "Jan Kowalski Rtec",
        "Jan Kowalski Thallium",
        "Jan Kowalski Tal",
        "Jan Kowalski Lead",
        "Jan Kowalski Ołów",
        "Jan Kowalski Olow",
        "Jan Kowalski Bismuth",
        "Jan Kowalski Bizmut",
        "Jan Kowalski Polonium",
        "Jan Kowalski Polon",
        "Jan Kowalski Astatine",
        "Jan Kowalski Astat",
        "Jan Kowalski Radon",
        "Jan Kowalski Radon",
        "Jan Kowalski Francium",
        "Jan Kowalski Frans",
        "Jan Kowalski Radium",
        "Jan Kowalski Rad",
        "Jan Kowalski Actinium",
        "Jan Kowalski Aktyn",
        "Jan Kowalski Thorium",
        "Jan Kowalski Tor",
        "Jan Kowalski Protactinium",
        "Jan Kowalski Protaktyn",
        "Jan Kowalski Uranium",
        "Jan Kowalski Uran",
        "Jan Kowalski Neptunium",
        "Jan Kowalski Neptun",
        "Jan Kowalski Plutonium",
        "Jan Kowalski Pluton",
        "Jan Kowalski Americium",
        "Jan Kowalski Ameryk",
        "Jan Kowalski Curium",
        "Jan Kowalski Kiur",
        "Jan Kowalski Berkelium",
        "Jan Kowalski Berkel",
        "Jan Kowalski Californium",
        "Jan Kowalski Kaliforn",
        "Jan Kowalski Einsteinium",
        "Jan Kowalski Einstein",
        "Jan Kowalski Fermium",
        "Jan Kowalski Ferm",
        "Jan Kowalski Mendelevium",
        "Jan Kowalski Mendelew",
        "Jan Kowalski Nobelium",
        "Jan Kowalski Nobel",
        "Jan Kowalski Lawrencium",
        "Jan Kowalski Lawrenc",
        "Jan Kowalski Rutherfordium",
        "Jan Kowalski Rutherford",
        "Jan Kowalski Dubnium",
        "Jan Kowalski Dubn",
        "Jan Kowalski Seaborgium",
        "Jan Kowalski Seaborg",
        "Jan Kowalski Bohrium",
        "Jan Kowalski Bohr",
        "Jan Kowalski Hassium",
        "Jan Kowalski Hass",
        "Jan Kowalski Meitnerium",
        "Jan Kowalski Meitner",
        "Jan Kowalski Darmstadtium",
        "Jan Kowalski Darmstadt",
        "Jan Kowalski Roentgenium",
        "Jan Kowalski Roentgen",
        "Jan Kowalski Copernicium",
        "Jan Kowalski Copernic",
        "Jan Kowalski Nihonium",
        "Jan Kowalski Nihon",
        "Jan Kowalski Flerovium",
        "Jan Kowalski Flerov",
        "Jan Kowalski Moscovium",
        "Jan Kowalski Moscov",
        "Jan Kowalski Livermorium",
        "Jan Kowalski Livermor",
        "Jan Kowalski Tennessine",
        "Jan Kowalski Tenness",
        "Jan Kowalski Oganesson",
        "Jan Kowalski Oganess"
    ]
    
    print("Testowanie funkcji is_likely_person:")
    print("=" * 50)
    
    valid_count = 0
    invalid_count = 0
    
    for name in test_names:
        is_person, reason = is_likely_person(name)
        status = "✅" if is_person else "❌"
        print(f"{status} {name}: {reason}")
        
        if is_person:
            valid_count += 1
        else:
            invalid_count += 1
    
    print("=" * 50)
    print(f"Wyniki: {valid_count} poprawnych, {invalid_count} odrzuconych")
    
    # Test filtrowania
    print("\nTestowanie filtrowania listy:")
    print("=" * 50)
    
    sample_names = [
        "Jan Kowalski", "Podcast Show", "Anna Nowak", "Pogrzeb Joanny",
        "Piotr Pająk", "Warsaw Studio", "Włodzisław Duch"
    ]
    
    filtered = filter_person_names(sample_names)
    print(f"Przefiltrowane nazwy: {filtered}") 